# Generated by Django 4.0.2 on 2022-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/default.jpg', null=True, upload_to='uploads/avatars'),
        ),
    ]
