# Generated by Django 4.0.2 on 2022-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/default.jpg', upload_to='uploads/avatars'),
        ),
    ]
