# Generated by Django 4.0.2 on 2022-03-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deadline Soon', 'Deadline'), ('Overdue', 'Overdue'), ('Paused', 'Paused'), ('Done', 'Done')], default='Active', max_length=15),
        ),
    ]
